/* AUTOGENERATED FILE, DO NOT MODIFY */

typedef unsigned long long ulonglong_4096;

#ifdef UNUMBER_SIZE
#undef UNUMBER_SIZE
#endif
#define UNUMBER_SIZE 64

#ifdef UBASE_TYPE
#undef UBASE_TYPE
#endif
#define UBASE_TYPE ulonglong_4096

#ifdef Unumber
#undef Unumber
#endif
#define Unumber Unum_4096

#ifdef Cunumber
#undef Cunumber
#endif
#define Cunumber Cunum_4096

#ifdef cinc
#undef cinc
#endif
#define cinc cinc_4096

#ifdef cdec
#undef cdec
#endif
#define cdec cdec_4096

#ifdef cequal
#undef cequal
#endif
#define cequal cequal_4096

#ifdef cbitorder
#undef cbitorder
#endif
#define cbitorder cbitorder_4096

#ifdef cadd
#undef cadd
#endif
#define cadd cadd_4096

#ifdef cdiv_QnotND
#undef cdiv_QnotND
#endif
#define cdiv_QnotND cdiv_QnotND_4096

#ifdef cshr
#undef cshr
#endif
#define cshr cshr_4096

#ifdef cshl
#undef cshl
#endif
#define cshl cshl_4096

#ifdef csub
#undef csub
#endif
#define csub csub_4096

#ifdef cmul
#undef cmul
#endif
#define cmul cmul_4096

#ifdef ciszero
#undef ciszero
#endif
#define ciszero ciszero_4096

#ifdef cless
#undef cless
#endif
#define cless cless_4096

#ifdef ctozero
#undef ctozero
#endif
#define ctozero ctozero_4096

#ifdef cnewzero
#undef cnewzero
#endif
#define cnewzero cnewzero_4096

#ifdef csetbit1
#undef csetbit1
#endif
#define csetbit1 csetbit1_4096

#ifdef cgetbit
#undef cgetbit
#endif
#define cgetbit cgetbit_4096

#ifdef cinvert
#undef cinvert
#endif
#define cinvert cinvert_4096

#ifdef cisvalid
#undef cisvalid
#endif
#define cisvalid cisvalid_4096

#ifdef cpow
#undef cpow
#endif
#define cpow cpow_4096

#ifdef cpow2
#undef cpow2
#endif
#define cpow2 cpow2_4096

#ifdef cxxx
#undef cxxx
#endif
#define cxxx cxxx_4096
